# Default initial positions for rv4fld's ros2_control fake system

initial_positions:
  rv4fld_joint_1: 0
  rv4fld_joint_2: 0
  rv4fld_joint_3: 0
  rv4fld_joint_4: 0
  rv4fld_joint_5: 0
  rv4fld_joint_6: 0